name: tilewarper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - gdal=3.0.2
  - xarray
  - numpy
  - pandas
  - pyproj
  - dask
  - netcdf4
  - pip:
    - equi7grid==0.0.10
    - pyraster==0.1.6
    - geopathfinder==0.0.7
